In [1]:
import numpy as np

In [4]:
v = np.zeros((1,9))

In [8]:
v[0,4] = 1

In [9]:
print(v)

[[0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [10]:
import numpy as np
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
import numpy as np
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.80157732 0.07505625 0.13971825]
  [0.73050652 0.61346447 0.63650543]
  [0.9585408  0.19059242 0.44613868]]

 [[0.57503461 0.66473444 0.39585343]
  [0.57259111 0.08022417 0.58267576]
  [0.99415876 0.24268393 0.82230737]]

 [[0.49811961 0.76820984 0.0663852 ]
  [0.6607006  0.92965198 0.14961589]
  [0.96648885 0.83821629 0.58829661]]]


In [15]:
import numpy as np

array = np.random.random((10, 10))

min_val = array.min()
max_val = array.max()

print("Array:\n", array)
print("\nMinimum value:", min_val)
print("Maximum value:", max_val)

Array:
 [[0.28942511 0.13821367 0.91536285 0.65442301 0.75521434 0.97894765
  0.40610415 0.72915709 0.79415918 0.91852797]
 [0.18956985 0.56363297 0.74345069 0.13054849 0.03304952 0.15557425
  0.16488057 0.87662066 0.82321067 0.64738469]
 [0.43681658 0.99870621 0.94435064 0.14036505 0.36492267 0.39903737
  0.71701613 0.18260802 0.50973939 0.16388038]
 [0.61912944 0.68703155 0.54739667 0.85882875 0.08325879 0.56184461
  0.77480444 0.41150218 0.41188426 0.68235326]
 [0.63574011 0.56058526 0.12574801 0.26541746 0.12165146 0.11353171
  0.75923489 0.31369944 0.96804865 0.3822487 ]
 [0.90191219 0.4477424  0.04972969 0.85172648 0.24444878 0.75045054
  0.63398775 0.94228473 0.59555105 0.73904467]
 [0.62709379 0.49833489 0.78946487 0.35980902 0.07969051 0.80184828
  0.08211145 0.81551532 0.65302274 0.888506  ]
 [0.48716972 0.24483156 0.3843676  0.99484849 0.60570271 0.97058579
  0.65488377 0.5110793  0.19226988 0.06858727]
 [0.50299978 0.96903038 0.12621447 0.6295347  0.75245617 0.57445613
  0.

In [16]:
import numpy as np

In [17]:
vector = np.random.random(30)

In [21]:
mean_val = vector.mean()

In [24]:
print("\n Vector: ", vector)
print("\n Mean Value: ", mean_val)


 Vector:  [0.13987368 0.37426123 0.09513213 0.33713438 0.20115073 0.47242611
 0.08386456 0.54133049 0.17269271 0.02234938 0.91703192 0.26561394
 0.04143163 0.25895424 0.62288583 0.52683831 0.62592167 0.05359786
 0.98307076 0.57947413 0.6795315  0.12210304 0.38247953 0.03956985
 0.57727142 0.74478016 0.93254085 0.56723585 0.846334   0.15675433]

 Mean Value:  0.41212120707620065


In [32]:
import numpy as np
array = np.ones((10, 10),)
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [33]:
import numpy as np
cb = np.zeros((6, 6))
cb[1::2, ::2] = 1
cb[::2, 1::2] = 1
print(cb)

[[0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]]


In [34]:
import numpy as np

matrix = np.zeros((5, 5), dtype=int)

matrix[1,0] = 1
matrix[2,1] = 2
matrix[3,2] = 3
matrix[4,3] = 4

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
