In [2]:
import numpy as np

In [3]:
x = np.array ([1,2,3])

In [4]:
print (type(x))

<class 'numpy.ndarray'>


In [5]:
print (x.shape)

(3,)


In [6]:
print (x[0], x[1], x[2],)

1 2 3


In [7]:
x[1] = 5

In [8]:
print (x)

[1 5 3]


In [10]:
y = np.array ([[1,2,3], [4,5,6]])

In [11]:
print (y.shape)

(2, 3)


In [12]:
print (y[0,0], y[0,1], y[1,1], y[1,2])

1 2 5 6


In [13]:
z = np.zeros ((2,2))

In [14]:
print (z)

[[0. 0.]
 [0. 0.]]


In [15]:
print(z)

[[0. 0.]
 [0. 0.]]


In [16]:
k = np.ones((2,3))

In [17]:
print(k)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
p = np.full ((2,3), 8 )

In [19]:
print(p)

[[8 8 8]
 [8 8 8]]


In [20]:
p[1,1] = 9 

In [21]:
print(p)

[[8 8 8]
 [8 9 8]]


In [22]:
e = np.random.random ((2,2))
print(e)

[[0.4308445  0.76911932]
 [0.3989058  0.85795662]]


In [23]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [24]:
row_r1 = a [1, :]
print (row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [26]:
col_r1 = a[:, 1]
print (col_r1, col_r1.shape)

[ 2  6 10] (3,)


In [27]:
print (a[0,0], a[1,1], a[2,0])

1 6 9


In [28]:
a = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11 ,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
r = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(r)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
r[1,1] = 50

In [31]:
print(r)

[[ 1  2  3]
 [ 4 50  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
d = np.array ([0,2,0,2])

In [33]:
print(r[np.arange(4), d])

[ 1  6  7 12]


In [35]:
r[np.arange(4), d] += 10
print(r)

[[11  2  3]
 [ 4 50 16]
 [17  8  9]
 [10 11 22]]


In [36]:
import numpy as np

In [37]:
bo = np.array ([[1,2], [3,4], [5,6]])

In [38]:
bool_idx = (bo > 2)
print (bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [39]:
print (bo[bool_idx])

[3 4 5 6]


In [40]:
print (bo[bo > 2])

[3 4 5 6]


In [41]:
bo = np.array ([[1,2], [3,4], [5,6]])

In [42]:
print (bo.dtype)

int64


In [44]:
bo = np.array ([[1,2.0], [3.0, 4], [5,6]])
print(bo.dtype)

float64


In [47]:
x = np.array ([[1,2], [3,4]])
y = np.array ([[3,4], [5,6]])

In [48]:
print (x+y)

[[ 4  6]
 [ 8 10]]


In [49]:
print (x-y)

[[-2 -2]
 [-2 -2]]


In [51]:
print (np.add(x,y))

[[ 4  6]
 [ 8 10]]


In [52]:
print (np.sum(x))

10


In [53]:
print (np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [54]:
print (x/y)

[[0.33333333 0.5       ]
 [0.6        0.66666667]]


In [55]:
print (x*y)

[[ 3  8]
 [15 24]]


In [56]:
print (np.multiply(x,y))
print (np.divide(x,y))
print (np.subtract(x,y))

[[ 3  8]
 [15 24]]
[[0.33333333 0.5       ]
 [0.6        0.66666667]]
[[-2 -2]
 [-2 -2]]


In [57]:
x = np.array ([[1,2], [3,4]])
y = np.array ([[5,6], [7,8]])

v = np.array ([9,10])
w = np.array ([11,12])

In [59]:
print (v.dot(w))
print (np.dot(v, w))

219
219


In [60]:
print (x.dot(w))
print (np.dot(x, v))

[35 81]
[29 67]


In [61]:
print (x.dot(v))
print (np.dot(x, v))

[29 67]
[29 67]


In [62]:
print (x.dot(y))
print (np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [63]:
x = np.array ([[1,2], [3,4]])
print (x)

[[1 2]
 [3 4]]


In [64]:
print (x.T)

[[1 3]
 [2 4]]


In [65]:
x = np.array ([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array ([1,0,1])

In [66]:
print (v+x)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [67]:
v = np.array ([1,2])
w = np.array ([4,5])
print (v*w)

[ 4 10]


In [68]:
v = np.array ([1,2,3])
w = np.array ([4,5])

In [69]:
print (np.reshape(v, (3,1))* w)

[[ 4  5]
 [ 8 10]
 [12 15]]
